stages:
  - test
  - name: release
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      language: go
      go: 'stable'
      script:
        - make tests
    
    - stage: release
      language: node_js
      install:
        - . $HOME/.nvm/nvm.sh
        - nvm install stable
        - nvm use stable
        - npm install @semantic-release/changelog && npm install @semantic-release/git
      script:
        - npx semantic-release
    
    